language: android
jdk: oraclejdk8

jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.groovy/grapes/

env:
  matrix:
    - TASK=:backend:test
    - TASK=:common-client-jvm:test
    - TASK=:common-client-js:test

script:
  - ./gradlew -Dorg.gradle.project.INCLUDE_ANDROID=false ${TASK}

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle