language: android
jdk: oraclejdk8

jdk:
  - oraclejdk8

env:
  matrix:
    - TASK=:backend:test
    - TASK=:common-client-jvm:test
    - TASK=:common-client-js:test

script:
  - ./gradlew -Dorg.gradle.project.INCLUDE_ANDROID=false ${TASK}

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle