language: android
jdk: oraclejdk8

jdk:
  - oraclejdk8

script:
  - ./gradlew -Dorg.gradle.project.INCLUDE_ANDROID=false testAll

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle